version: "3.7"

services:
  web:
    image: registry.gitlab.com/steffbeckers/balls
    networks:
      - reverse-proxy_default
    deploy:
      mode: replicated
      replicas: 2

networks:
  reverse-proxy_default:
    external: true
